package com.sapuseven.sneakybot.plugin.r6siege.enums

enum class Rank(val displayName: String) {
	UNRANKED("Unranked"),
	COPPER_5("Copper V"),
	COPPER_4("Copper IV"),
	COPPER_3("Copper III"),
	COPPER_2("Copper II"),
	COPPER_1("Copper I"),
	BRONZE_5("Bronze V"),
	BRONZE_4("Bronze IV"),
	BRONZE_3("Bronze III"),
	BRONZE_2("Bronze II"),
	BRONZE_1("Bronze I"),
	SILVER_5("Silver V"),
	SILVER_4("Silver IV"),
	SILVER_3("Silver III"),
	SILVER_2("Silver II"),
	SILVER_1("Silver I"),
	GOLD_5("Gold V"),
	GOLD_4("Gold IV"),
	GOLD_3("Gold III"),
	GOLD_2("Gold II"),
	GOLD_1("Gold I"),
	PLATINUM_5("Platinum V"),
	PLATINUM_4("Platinum IV"),
	PLATINUM_3("Platinum III"),
	PLATINUM_2("Platinum II"),
	PLATINUM_1("Platinum I"),
	EMERALD_5("Emerald V"),
	EMERALD_4("Emerald IV"),
	EMERALD_3("Emerald III"),
	EMERALD_2("Emerald II"),
	EMERALD_1("Emerald I"),
	DIAMOND_5("Diamond V"),
	DIAMOND_4("Diamond IV"),
	DIAMOND_3("Diamond III"),
	DIAMOND_2("Diamond II"),
	DIAMOND_1("Diamond I"),
	CHAMPIONS("Champions");
}
