name: Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload SneakyBOT artifacts
      uses: actions/upload-artifact@v1
      with:
        name: SneakyBOT
        path: sneakybot/build/distributions/
    - name: Upload SneakyBOT plugin artifacts
      uses: actions/upload-artifact@v1
      with:
        name: SneakyBOT Plugins
        path: plugins/
